# Generated by Django 5.0.7 on 2024-07-22 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_category_description_alter_product_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'products'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_image',
            new_name='products_image',
        ),
    ]
